#ifndef _VND_BUILDCFG_H
#define _VND_BUILDCFG_H
#define BLUETOOTH_UART_DEVICE_PORT   "/dev/ttyHS0"
#define FW_PATCHFILE_LOCATION   "/vendor/firmware/"
#define BT_WAKE_VIA_PROC   TRUE
#define BT_WAKE_VIA_PROC_NOTIFY_DEASSERT   TRUE
#define BT_WAKE_VIA_USERIAL_IOCTL   FALSE
#define PROC_BTWRITE_TIMER_TIMEOUT_MS   0
#define UART_TARGET_BAUD_RATE   3000000
#define LPM_IDLE_TIMEOUT_MULTIPLE   5
#define LPM_BT_WAKE_POLARITY   0
#define LPM_HOST_WAKE_POLARITY   0
#define SCO_USE_I2S_INTERFACE   FALSE
#define SCO_I2SPCM_IF_ROLE   0
#define BTVND_DBG   FALSE
#define BTHW_DBG   TRUE
#define VNDUSERIAL_DBG   FALSE
#define UPIO_DBG   FALSE
#endif
